# Generated by Django 4.1.4 on 2022-12-30 23:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=26)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=56)),
            ],
        ),
        migrations.CreateModel(
            name='ListaVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=3, max_digits=5)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=16)),
                ('descricao', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.DecimalField(decimal_places=3, max_digits=5)),
                ('desconto', models.DecimalField(decimal_places=3, max_digits=5)),
                ('data', models.DateField(default=datetime.date.today)),
                ('produtos', models.ManyToManyField(to='app.listavenda')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=126)),
                ('preco', models.DecimalField(decimal_places=4, max_digits=6)),
                ('margemVenda', models.DecimalField(decimal_places=3, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=4, max_digits=6)),
                ('medidas', models.CharField(max_length=56)),
                ('qntEstoque', models.IntegerField()),
                ('qntMin', models.IntegerField()),
                ('codExterno', models.CharField(max_length=125, null=True)),
                ('dataCadastro', models.DateField(default=datetime.date.today)),
                ('dataModificacao', models.DateField(default=datetime.date.today)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.grupo')),
                ('unidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.unidade')),
            ],
        ),
        migrations.AddField(
            model_name='listavenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto'),
        ),
    ]
